---
- hosts: all
  tasks:
    - name: test
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
        permanent: true
      when: ansible_hostname != 'awx'
